#!/bin/bash

LOCAL_RANK=${OMPI_COMM_WORLD_LOCAL_RANK:-${MPI_LOCALRANKID:-${SLURM_LOCALID:-0}}}
export LOCAL_RANK

export CUDA_VISIBLE_DEVICES=${LOCAL_RANK}
export HIP_VISIBLE_DEVICES=${LOCAL_RANK}
export ROCR_VISIBLE_DEVICES=${LOCAL_RANK}
export OMP_DEFAULT_DEVICE=${LOCAL_RANK}

echo "[LOG] local rank ${LOCAL_RANK}: bind to CUDA=${CUDA_VISIBLE_DEVICES} HIP=${HIP_VISIBLE_DEVICES} ROCR=${ROCR_VISIBLE_DEVICES} OMP=${OMP_DEFAULT_DEVICE}"
echo ""

exec "$@"
