# This is a basic workflow to help you get started with Actions
name: FullCI4PR_intel_single

defaults:
  run:
    shell: bash 

# Controls when the action will run. Triggers the workflow on pull request
# events but only for the master branch
on: [pull_request, fork]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a job called "bld_gnu_ompi"
  Full_CI_INTEL_single:
    # The type of runner that the job will run on
    runs-on: [self-hosted, linux, x64]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v4
      with: 
        clean: true
    
    # Configure-Build-Run-Run on 4 cores 
    - name: Compile Intel MKL CPU
      run: |
        ls -ltr ~/.bashrc
        source /etc/profile.d/lmod.sh
        source ~/.bash_aliases
        ml tbb
        ml compiler-rt
        ml oclfpga
        ml compiler
        ml mpi
        ml mkl
        export FC=mpiifx
        export MKL_DIR=${MKLROOT}/lib/cmake/mkl
        cmake -S . -B build -DDOUBLE_PRECISION=OFF -DCMAKE_BUILD_TYPE=Dev -DBUILD_TESTING=ON -DFFT_Choice=mkl
        cmake -S . -B build -DNX=128 -DNY=128 -DNX=128 -DMPIEXEC_MAX_NUMPROCS=4
        cmake --build build -j 4
        cmake --install build 
        ctest --test-dir build --output-on-failure
        rm -rf build  
    
    # Configure-Build-Run-Run on 4 cores 
    - name: Compile IntelLLVM MKL CPU
      run: |
        ls -ltr ~/.bashrc
        source /etc/profile.d/lmod.sh
        source ~/.bash_aliases
        ml tbb
        ml compiler-rt
        ml oclfpga
        ml compiler
        ml mpi
        ml mkl
        export FC=mpiifx
        export MKL_DIR=${MKLROOT}/lib/cmake/mkl
        cmake -S . -B build -DDOUBLE_PRECISION=OFF -DCMAKE_BUILD_TYPE=Dev -DBUILD_TESTING=ON -DFFT_Choice=mkl
        cmake -S . -B build -DNX=128 -DNY=128 -DNX=128 -DMPIEXEC_MAX_NUMPROCS=4
        cmake --build build -j 4
        cmake --install build 
        ctest --test-dir build --output-on-failure
        rm -rf build 

    # Configure-Build-Run-Run on 4 cores 
    - name: Compile IntelLLVM MKL ADIOS2 CPU
      run: |
        ls -ltr ~/.bashrc
        source /etc/profile.d/lmod.sh
        source ~/.bash_aliases
        ml tbb
        ml compiler-rt
        ml oclfpga
        ml compiler
        ml mpi
        ml mkl
        export FC=mpiifx
        export CC=mpiicx
        export CXX=mpiicpx
        export MKL_DIR=${MKLROOT}/lib/cmake/mkl
        cmake -S . -B build -DCMAKE_BUILD_TYPE=Dev -DDOUBLE_PRECISION=OFF -DBUILD_TESTING=ON -DIO_BACKEND=adios2 -Dadios2_DIR=~/GIT/ADIOS2/build/build_intelLLVM/opt/lib/cmake/adios2 -DFFT_Choice=mkl
        cmake -S . -B build -DNX=128 -DNY=128 -DNX=128 -DMPIEXEC_MAX_NUMPROCS=4
        cmake --build build -j 4
        cmake --install build
        ctest --test-dir build --output-on-failure
        rm -rf build
